### ISSUE TITLE
SSR compatibility?

### ISSUE THREAD

**Issue by RezaHaidari** [monterail/vue-multiselect#137] opened 2016-10-31 05:37 UTC
vue-multiselect doesn't work in server-side rendering, vue-multiselect has compatibility with ssr?

**Comment by martinherweg** [comment] 2016-11-01 17:48
I gave it a shot yesterday, after some trial and error I think the plugin itself is working fine, the problem is that the style-loader for webpack in the bundle relies on the window object and therefore the script throws an error during SSR.

I made a custom bundle without the Style Loader and SSR was working, problem then was just the styling which could be resolved by using an external stylesheet.

**Comment by shentao** [comment] 2016-11-01 19:55
Hey @martinherweg! Thanks for trying it and the suggestion. I will try to resolve this issue after finishing groups.

**Comment by shilka** [comment] 2016-11-08 18:55
@martinherweg Hi! Is there any way to workaround or patch it until this issue will be resolved?

**Comment by shentao** [comment] 2016-11-08 20:11
Sadly not yet. :(

**Comment by martinherweg** [comment] 2016-11-09 00:05
@shilka I made a fork and changed webpack to extract the stylesheet instead of injecting it.

Not the best way so i did'nt submit a PR

https://github.com/martinherweg/vue-multiselect/tree/2.0

**Comment by shyamchandranmec** [comment] 2017-02-21 06:18
@shentao Does it work with SSR now?

**Comment by shyamchandranmec** [comment] 2017-02-22 06:58
@shentao  I tried this with SSR. I am using nuxt.js for SSR. It still doesn't work. It shows 
   
   ReferenceError: window is not defined

I wanted to use this plugin in my project. Could you please tell when you are planning to fix this.

**Comment by shentao** [comment] 2017-02-22 07:28
Hey. It was supposed to be fixed already, just have to publish the new version. But just can't find the time to do it. I hope I can make it today or tomorrow.

**Comment by shyamchandranmec** [comment] 2017-02-22 07:31
@shentao Thanks for the quick reply.This is the best plugin I could find which covers all the use cases. It will be really helpful if you can do it soon.

**Comment by shentao** [comment] 2017-02-25 13:52
@shyamchandranmec @martinherweg @RezaHaidari @pitersky beta.14 released and should fix this problem. Sorry you had to wait so long :(
Please read: https://github.com/monterail/vue-multiselect/blob/2.0/README.md
Breaking change regarding the styles.

**Closed by shentao** 2017-02-25 13:52 UTC
Labels: enhancement

**Comment by jazoom** [comment] 2017-02-26 02:07
Are you saying that's a breaking change from beta 13? I thought that was the same before.

**Comment by shentao** [comment] 2017-02-26 09:44
Yeah, I published the package to not make anyone wait any longer. Some of the fixes were already done a month ago, just the release took so long to happen. 
Today I will prepare the release notes and update the docs, freeze the development on 2.0 apart from small bug fixes and release it as the new stable version (tagged as `latest`) in the coming days. The current master will become 1.x which will be mostly for small fixes and community contributions, though I would recommend everyone to migrate to Vue 2.0.
After already having a stable 2.0 release I could release the beta/dev versions much more often. And then regularly (if there are no crucial bugs) – update the stable release.


| Source branch | New branch | Release tag |
| --- | --- | --- |
| master | 1.x | 1.x |
| 2.0 | master | latest (default) |
| 2.0 | dev | next (currently known as beta) |

I hope that those changes will help improve the time between releases and the release cycle in general. Those should reduce the pressure on making sure the new beta has no known bugs before a new release, as using it will be completely opt-in,

**Comment by jazoom** [comment] 2017-02-27 00:02
You're doing great work
